# Generated by Django 3.0.7 on 2020-07-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='phone_two',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
