# Generated by Django 3.0.7 on 2020-07-06 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_realtor_phone_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='phone_two',
        ),
    ]
